version: "3"

networks:
  web:
    external: true

services:
  site:
    build: .
    restart: always
    labels:
      - traefik.backend=itrium-test
      - traefik.frontend.rule=Host:itrium.adorazel.online
      - traefik.docker.network=web
      - traefik.port=5000
    networks:
      - web



