version: "3"

networks:
  web:
    external: true

services:
  itrium:
    build: .
    restart: always
    labels:
      - traefik.backend=itrium
      - traefik.frontend.rule=Host:itrium.adorazel.online
      - traefik.docker.network=web
      - traefik.port=5000
    networks:
      - web