version: "3"

networks:
  itrium_web:
    external: true

services:
  itrium:
    build: .
    restart: always
    labels:
      - traefik.backend=itrium-test
      - traefik.frontend.rule=Host:itrium.adorazel.online
      - traefik.docker.network=itrium_web
      - traefik.port=5000
    networks:
      - itrium_web