
export const SET_FETCH_LOADING = "SET_FETCH_LOADING"
export const SET_FETCH_SUCCESS = "SET_FETCH_SUCCESS"
export const SET_FETCH_FAILURE = "SET_FETCH_FAILURE"

export const SET_REQUEST_ERROR = "SET_REQUEST_ERROR"
export const SET_REQUEST_URL = "SET_REQUEST_URL"
export const SET_REQUEST_METHOD = "SET_REQUEST_METHOD"
export const SET_REQUEST_HEADERS = "SET_REQUEST_HEADERS"
export const SET_REQUEST_BODY = "SET_REQUEST_BODY"

export const SET_RESPONSE_ERROR = "SET_RESPONSE_ERROR"
export const SET_RESPONSE_STATUS_CODE = "SET_RESPONSE_STATUS_CODE"
export const SET_RESPONSE_HEADERS = "SET_RESPONSE_HEADERS"
export const SET_RESPONSE_BODY = "SET_RESPONSE_BODY"